apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/blue-sts.yaml
  - ../../base/blue-green-service.yaml
  - ../../base/blue-green-ing.yaml
  - ../../base/config-blue-green.yaml

patchesStrategicMerge:
  - patch-blue-service.yaml

