apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/blue-sts.yaml
  - ../../base/nginx-service-blue.yaml
  - ../../base/blue-green-ing.yaml
  - ../../base/config-blue-green.yaml

patchesStrategicMerge:
  - patch-ingress-blue.yaml

