apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/egangithub1502/nginx-blue-green'
    targetRevision: HEAD
    path: html-nginx-app/overlays/blue   # <<< update this path!
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

