apiVersion: v1
kind: Service
metadata:
  name: nginx-service-green
  namespace: nginx
  labels:
    app: nginx
    color: green
    enabled: "true"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: nginx
    color: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

